name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: |
            python-wheels-ubuntu-latest-3.9
            python-wheels-ubuntu-latest-3.10
            python-wheels-ubuntu-latest-3.11
            python-wheels-ubuntu-latest-3.12
            python-wheels-macos-latest-3.9
            python-wheels-macos-latest-3.10
            python-wheels-macos-latest-3.11
            python-wheels-macos-latest-3.12
            python-wheels-windows-latest-3.9
            python-wheels-windows-latest-3.10
            python-wheels-windows-latest-3.11
            python-wheels-windows-latest-3.12
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine

      - name: Test publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
