name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9, "3.10", "3.11", "3.12"] # Add more versions as needed
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Run tests
        run: |
          poetry run pytest . -vv

      - name: Lint with Black
        run: |
          poetry run black --check .

      - name: Build wheels
        run: |
          poetry build -f wheel
        env:
          CIBW_SKIP: pp* cp27* cp34* cp35* cp36* cp37* cp38*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-${{ matrix.os }}-${{ matrix.python-version }}
          path: dist/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine

      - name: Test publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          twin upload dist/*/*.whl
